name: SuperTickets
main: me.datdenkikniet.Supertickets
version: 0.2.1
commands:
    supertickets:
        description: main supertickets command
    st:
        description: main supertickets command